# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.create(first_name: "test", last_name: "user", email: 'test@test.com', password: '12345678', password_confirmation: '12345678')

@q1 = user.questionnaires.create(name: "Relationship System")

@question1 = @q1.questions.create(content: "What is your partners name?")
@question2 = @q1.questions.create(content: "Is your relationship important to you?")
@question2.options.create(content: 'Yes')
@question2.options.create(content: 'No')

@question3 = @q1.questions.create(content: "When you feel most connected to [A1] do you feel? (Pick Two)")
@question3.options.create(content: "Accepted By")
@question3.options.create(content: "Heard By")
@question3.options.create(content: "Seen By")
@question3.options.create(content: "Understood By")
@question3.options.create(content: "Affirmed By")
@question3.options.create(content: "Reflected positively By")
@question3.options.create(content: "Bonded to")
@question3.options.create(content: "Honored By")
@question3.options.create(content: "Valued By")
@question3.options.create(content: "Important to")
@question3.options.create(content: "Loved By")
@question3.options.create(content: "Acknowledged By")
@question3.options.create(content: "Appreciated By")
@question3.options.create(content: "Reassured By")
@question3.options.create(content: "Treasure By")
@question3.options.create(content: "Respected By")
@question3.options.create(content: "Prized By")
@question3.options.create(content: "Precious To")
@question3.options.create(content: "Admired By")
@question3.options.create(content: "Liked By")
@question3.options.create(content: "Adored By")
@question3.options.create(content: "Cherished By")
@question3.options.create(content: "Cared For By")
@question3.options.create(content: "Comforted By")
@question3.options.create(content: "Held By")
@question3.options.create(content: "Embraced By")
@question3.options.create(content: "Special To")
@question3.options.create(content: "A Priority To")
@question3.options.create(content: "Wanted To")
@question3.options.create(content: "Desired By")
@question3.options.create(content: "Safe With")

@question4 = @q1.questions.create(content: "[Current User] when you and [A1] are disconnected how would you describe [A1]?(Pick 2)")
@question4.options.create(content: "Mean")
@question4.options.create(content: "Selfish")
@question4.options.create(content: "Dramatic")
@question4.options.create(content: "Uncaring")
@question4.options.create(content: "Aggressive")
@question4.options.create(content: "Cold")
@question4.options.create(content: "Attacking")
@question4.options.create(content: "Angry")
@question4.options.create(content: "Mad")
@question4.options.create(content: "Crazy")
@question4.options.create(content: "Unsafe")
@question4.options.create(content: "Judgemental")
@question4.options.create(content: "Critical")
@question4.options.create(content: "A Complainer")
@question4.options.create(content: "Unloving")
@question4.options.create(content: "Controlling")
@question4.options.create(content: "Condesending")
@question4.options.create(content: "Self-Righteous")
@question4.options.create(content: "Nagging")
@question4.options.create(content: "Clingy")
@question4.options.create(content: "Demanding")
@question4.options.create(content: "Blaming")
@question4.options.create(content: "Argumentative")
@question4.options.create(content: "Disapproving")
@question4.options.create(content: "Not Present")
@question4.options.create(content: "Invasive")
@question4.options.create(content: "Cruel")
@question4.options.create(content: "Distracted")
@question4.options.create(content: "Defensive")
@question4.options.create(content: "Avoidant")
@question4.options.create(content: "A Minimizer")
@question4.options.create(content: "Mocking")
@question4.options.create(content: "Unresponsive")
@question4.options.create(content: "Dismissive")
@question4.options.create(content: "Shut-Down")
@question4.options.create(content: "Withdrawn")
@question4.options.create(content: "Numbed Out")

@question5 = @q1.questions.create(content: "[Current User], when [A1] appears to be [A4a] and [A4b] how do you feel? (Pick 2)")
@question5.options.create(content: "Angry")
@question5.options.create(content: "Frustrated")
@question5.options.create(content: "Disappointed")
@question5.options.create(content: "Aggitated")
@question5.options.create(content: "Cold")
@question5.options.create(content: "Disapproving")
@question5.options.create(content: "Anxious")
@question5.options.create(content: "Disdainful")
@question5.options.create(content: "Hostile")
@question5.options.create(content: "Persecuted")
@question5.options.create(content: "Distrusing")
@question5.options.create(content: "Jealous")
@question5.options.create(content: "Worried")
@question5.options.create(content: "Insecure")
@question5.options.create(content: "Confused")
@question5.options.create(content: "Enraged")
@question5.options.create(content: "Contemptful")
@question5.options.create(content: "Dissatisfied")
@question5.options.create(content: "Guilty")
@question5.options.create(content: "Annoyed")
@question5.options.create(content: "Exasperated")
@question5.options.create(content: "Peeved")
@question5.options.create(content: "Incensed")
@question5.options.create(content: "Riled")
@question5.options.create(content: "Irked")
@question5.options.create(content: "Distressed")
@question5.options.create(content: "Antagonistic")
@question5.options.create(content: "Resentful")
@question5.options.create(content: "Sullen")

@question6 = @q1.questions.create(content: "  When you see [A1] as [A4a] and [A4b], and you are feeling [A5a] and [A5b] what do you do? (Pick 2)")
@question6.options.create(content: "Probe")
@question6.options.create(content: "Complain")
@question6.options.create(content: "Pick")
@question6.options.create(content: "Attack")
@question6.options.create(content: "Put down")
@question6.options.create(content: "Criticize")
@question6.options.create(content: "Question")
@question6.options.create(content: "Advise")
@question6.options.create(content: "Joke")
@question6.options.create(content: "Minimize")
@question6.options.create(content: "Argue")
@question6.options.create(content: "Clam up")
@question6.options.create(content: "Attack")
@question6.options.create(content: "Yell")
@question6.options.create(content: "Judge")
@question6.options.create(content: "Withdraw")
@question6.options.create(content: "Disapprove")
@question6.options.create(content: "Avoid")
@question6.options.create(content: "Freeze")
@question6.options.create(content: "Go mute")
@question6.options.create(content: "Collapse")
@question6.options.create(content: "Numb out")
@question6.options.create(content: "Appease")
@question6.options.create(content: "Dismiss")


@question7 = @q1.questions.create(content: "[Current User], Being disconnected sucks!! When you see [A1] as [A4a] and [A4b] and you are feeling [A5a] and [A5b] which of the following best describes what it feels like deep inside? (Pick 2)")
@question7.options.create(content: "Unseen")
@question7.options.create(content: "Unloved")
@question7.options.create(content: "Uncared For")
@question7.options.create(content: "Alone")
@question7.options.create(content: "Abandoned")
@question7.options.create(content: "Rejected")
@question7.options.create(content: "Powerless")
@question7.options.create(content: "Scared")
@question7.options.create(content: "Ashamed")
@question7.options.create(content: "Hearbroken")
@question7.options.create(content: "Isolated")
@question7.options.create(content: "Sad")
@question7.options.create(content: "Hopeless")
@question7.options.create(content: "Despair")
@question7.options.create(content: "Grief")
@question7.options.create(content: "Panic")
@question7.options.create(content: "Disliked")
@question7.options.create(content: "Desserted")
@question7.options.create(content: "Left")
@question7.options.create(content: "Withdrawn")
@question7.options.create(content: "Empty")
@question7.options.create(content: "Spurned")
@question7.options.create(content: "Unvalued")
@question7.options.create(content: "Unwelcome")
@question7.options.create(content: "Stuck")
@question7.options.create(content: "Emotional Pain")

@question8 = @q1.questions.create(content: "When you are feeling [A7a] and [A7b] do you ever see yourself as being any of the following? (Pick 2)")
@question8.options.create(content: "Undesirable")
@question8.options.create(content: "Unattractive")
@question8.options.create(content: "Useless")
@question8.options.create(content: "Needy")
@question8.options.create(content: "Powerless")
@question8.options.create(content: "Weak")
@question8.options.create(content: "Wimpy")
@question8.options.create(content: "Unlikeable")
@question8.options.create(content: "Unloveable")
@question8.options.create(content: "Broken")
@question8.options.create(content: "Too Much")
@question8.options.create(content: "Not Enough")
@question8.options.create(content: "A Failure")
@question8.options.create(content: "Worthless")
@question8.options.create(content: "Deficient")
@question8.options.create(content: "Inadequate")
@question8.options.create(content: "Unacceptable")
@question8.options.create(content: "Undeserving")
@question8.options.create(content: "Inferior")
@question8.options.create(content: "Blameworthy")
@question8.options.create(content: "Damaged")

@question9 = @q1.questions.create(content: "[Current User], in moments when you feel you are [A8a] and [A8b] and [A7a] and [A7b] how do you imagine you appear to [A1]? (Pick 2)")
@question9.options.create(content: "Undesirable")
@question9.options.create(content: "Unattractive")
@question9.options.create(content: "Weak")
@question9.options.create(content: "Useless")
@question9.options.create(content: "Needy")
@question9.options.create(content: "Powerless")
@question9.options.create(content: "Wimpy")
@question9.options.create(content: "Unlikeable")
@question9.options.create(content: "Too Much")
@question9.options.create(content: "Unloveable")
@question9.options.create(content: "Not Enough")
@question9.options.create(content: "A Failure")
@question9.options.create(content: "Worthless")
@question9.options.create(content: "Deficient")
@question9.options.create(content: "Inadequate")
@question9.options.create(content: "Undeserving")
@question9.options.create(content: "Inferior")
@question9.options.create(content: "Blameworthy")
@question9.options.create(content: "Broken")
@question9.options.create(content: "Damaged")