# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

@q1 = Questionnaire.create(name: "Realtionship System")
@question1 = @q1.questions.create(body: "What is your partners name?")
@question2 = @q1.questions.create(body: "Is your relationship important to you?")
@question2.answers.create(body: 'Yes')
@question2.answers.create(body: 'No')

@question3 = @q1.questions.create(body: "When you feel most connected to [A1] do you feel? (Pick Two)")
@question3.answers.create(body: "Accepted By")
@question3.answers.create(body: "Heard By")
@question3.answers.create(body: "Seen By")
@question3.answers.create(body: "Understood By")
@question3.answers.create(body: "Affirmed By")
@question3.answers.create(body: "Reflected positively By")
@question3.answers.create(body: "Bonded to")
@question3.answers.create(body: "Honored By")
@question3.answers.create(body: "Valued By")
@question3.answers.create(body: "Important to")
@question3.answers.create(body: "Loved By")
@question3.answers.create(body: "Acknowledged By")
@question3.answers.create(body: "Appreciated By")
@question3.answers.create(body: "Reassured By")
@question3.answers.create(body: "Treasure By")
@question3.answers.create(body: "Respected By")
@question3.answers.create(body: "Prized By")
@question3.answers.create(body: "Precious To")
@question3.answers.create(body: "Admired By")
@question3.answers.create(body: "Liked By")
@question3.answers.create(body: "Adored By")
@question3.answers.create(body: "Cherished By")
@question3.answers.create(body: "Cared For By")
@question3.answers.create(body: "Comforted By")
@question3.answers.create(body: "Held By")
@question3.answers.create(body: "Embraced By")
@question3.answers.create(body: "Special To")
@question3.answers.create(body: "A Priority To")
@question3.answers.create(body: "Wanted To")
@question3.answers.create(body: "Desired By")
@question3.answers.create(body: "Safe With")

@question4 = @q1.questions.create(body: "[Current User] when you and [A1] are disconnected how would you describe [A1]?(Pick 2)")
@question4.answers.create(body: "Mean")
@question4.answers.create(body: "Selfish")
@question4.answers.create(body: "Dramatic")
@question4.answers.create(body: "Uncaring")
@question4.answers.create(body: "Aggressive")
@question4.answers.create(body: "Cold")
@question4.answers.create(body: "Attacking")
@question4.answers.create(body: "Angry")
@question4.answers.create(body: "Mad")
@question4.answers.create(body: "Crazy")
@question4.answers.create(body: "Unsafe")
@question4.answers.create(body: "Judgemental")
@question4.answers.create(body: "Critical")
@question4.answers.create(body: "A Complainer")
@question4.answers.create(body: "Unloving")
@question4.answers.create(body: "Controlling")
@question4.answers.create(body: "Condesending")
@question4.answers.create(body: "Self-Righteous")
@question4.answers.create(body: "Nagging")
@question4.answers.create(body: "Clingy")
@question4.answers.create(body: "Demanding")
@question4.answers.create(body: "Blaming")
@question4.answers.create(body: "Argumentative")
@question4.answers.create(body: "Disapproving")
@question4.answers.create(body: "Not Present")
@question4.answers.create(body: "Invasive")
@question4.answers.create(body: "Cruel")
@question4.answers.create(body: "Distracted")
@question4.answers.create(body: "Defensive")
@question4.answers.create(body: "Avoidant")
@question4.answers.create(body: "A Minimizer")
@question4.answers.create(body: "Mocking")
@question4.answers.create(body: "Unresponsive")
@question4.answers.create(body: "Dismissive")
@question4.answers.create(body: "Shut-Down")
@question4.answers.create(body: "Withdrawn")
@question4.answers.create(body: "Numbed Out")

@question5 = @q1.questions.create(body: "[Current User], when [A1] appears to be [A4a] and [A4b] how do you feel? (Pick 2)")
@question5.answers.create(body: "Angry")
@question5.answers.create(body: "Frustrated")
@question5.answers.create(body: "Disappointed")
@question5.answers.create(body: "Aggitated")
@question5.answers.create(body: "Cold")
@question5.answers.create(body: "Disapproving")
@question5.answers.create(body: "Anxious")
@question5.answers.create(body: "Disdainful")
@question5.answers.create(body: "Hostile")
@question5.answers.create(body: "Persecuted")
@question5.answers.create(body: "Distrusing")
@question5.answers.create(body: "Jealous")
@question5.answers.create(body: "Worried")
@question5.answers.create(body: "Insecure")
@question5.answers.create(body: "Confused")
@question5.answers.create(body: "Enraged")
@question5.answers.create(body: "Contemptful")
@question5.answers.create(body: "Dissatisfied")
@question5.answers.create(body: "Guilty")
@question5.answers.create(body: "Annoyed")
@question5.answers.create(body: "Exasperated")
@question5.answers.create(body: "Peeved")
@question5.answers.create(body: "Incensed")
@question5.answers.create(body: "Riled")
@question5.answers.create(body: "Irked")
@question5.answers.create(body: "Distressed")
@question5.answers.create(body: "Antagonistic")
@question5.answers.create(body: "Resentful")
@question5.answers.create(body: "Sullen")

@question6 = @q1.questions.create(body: "  When you see [A1] as [A4a] and [A4b], and you are feeling [A5a] and [A5b] what do you do? (Pick 2)")
@question6.answers.create(body: "Probe")
@question6.answers.create(body: "Complain")
@question6.answers.create(body: "Pick")
@question6.answers.create(body: "Attack")
@question6.answers.create(body: "Put down")
@question6.answers.create(body: "Criticize")
@question6.answers.create(body: "Question")
@question6.answers.create(body: "Advise")
@question6.answers.create(body: "Joke")
@question6.answers.create(body: "Minimize")
@question6.answers.create(body: "Argue")
@question6.answers.create(body: "Clam up")
@question6.answers.create(body: "Attack")
@question6.answers.create(body: "Yell")
@question6.answers.create(body: "Judge")
@question6.answers.create(body: "Withdraw")
@question6.answers.create(body: "Disapprove")
@question6.answers.create(body: "Avoid")
@question6.answers.create(body: "Freeze")
@question6.answers.create(body: "Go mute")
@question6.answers.create(body: "Collapse")
@question6.answers.create(body: "Numb out")
@question6.answers.create(body: "Appease")
@question6.answers.create(body: "Dismiss")


@question7 = @q1.questions.create(body: "[Current User], Being disconnected sucks!! When you see [A1] as [A4a] and [A4b] and you are feeling [A5a] and [A5b] which of the following best describes what it feels like deep inside? (Pick 2)")
@question7.answers.create(body: "Unseen")
@question7.answers.create(body: "Unloved")
@question7.answers.create(body: "Uncared For")
@question7.answers.create(body: "Alone")
@question7.answers.create(body: "Abandoned")
@question7.answers.create(body: "Rejected")
@question7.answers.create(body: "Powerless")
@question7.answers.create(body: "Scared")
@question7.answers.create(body: "Ashamed")
@question7.answers.create(body: "Hearbroken")
@question7.answers.create(body: "Isolated")
@question7.answers.create(body: "Sad")
@question7.answers.create(body: "Hopeless")
@question7.answers.create(body: "Despair")
@question7.answers.create(body: "Grief")
@question7.answers.create(body: "Panic")
@question7.answers.create(body: "Disliked")
@question7.answers.create(body: "Desserted")
@question7.answers.create(body: "Left")
@question7.answers.create(body: "Withdrawn")
@question7.answers.create(body: "Empty")
@question7.answers.create(body: "Spurned")
@question7.answers.create(body: "Unvalued")
@question7.answers.create(body: "Unwelcome")
@question7.answers.create(body: "Stuck")
@question7.answers.create(body: "Emotional Pain")

@question8 = @q1.questions.create(body: "When you are feeling [A7a] and [A7b] do you ever see yourself as being any of the following? (Pick 2)")
@question8.answers.create(body: "Undesirable")
@question8.answers.create(body: "Unattractive")
@question8.answers.create(body: "Useless")
@question8.answers.create(body: "Needy")
@question8.answers.create(body: "Powerless")
@question8.answers.create(body: "Weak")
@question8.answers.create(body: "Wimpy")
@question8.answers.create(body: "Unlikeable")
@question8.answers.create(body: "Unloveable")
@question8.answers.create(body: "Broken")
@question8.answers.create(body: "Too Much")
@question8.answers.create(body: "Not Enough")
@question8.answers.create(body: "A Failure")
@question8.answers.create(body: "Worthless")
@question8.answers.create(body: "Deficient")
@question8.answers.create(body: "Inadequate")
@question8.answers.create(body: "Unacceptable")
@question8.answers.create(body: "Undeserving")
@question8.answers.create(body: "Inferior")
@question8.answers.create(body: "Blameworthy")
@question8.answers.create(body: "Damaged")

@question9 = @q1.questions.create(body: "[Current User], in moments when you feel you are [A8a] and [A8b] and [A7a] and [A7b] how do you imagine you appear to [A1]? Pick two")
@question9.answers.create(body: "Undesirable")
@question9.answers.create(body: "Unattractive")
@question9.answers.create(body: "Weak")
@question9.answers.create(body: "Useless")
@question9.answers.create(body: "Needy")
@question9.answers.create(body: "Powerless")
@question9.answers.create(body: "Wimpy")
@question9.answers.create(body: "Unlikeable")
@question9.answers.create(body: "Too Much")
@question9.answers.create(body: "Unloveable")
@question9.answers.create(body: "Not Enough")
@question9.answers.create(body: "A Failure")
@question9.answers.create(body: "Worthless")
@question9.answers.create(body: "Deficient")
@question9.answers.create(body: "Inadequate")
@question9.answers.create(body: "Undeserving")
@question9.answers.create(body: "Inferior")
@question9.answers.create(body: "Blameworthy")
@question9.answers.create(body: "Broken")
@question9.answers.create(body: "Damaged")